### ISSUE TITLE
Won't reconnect without closing and reopening app.

### ISSUE THREAD

**Issue by bhartsb** [socketio/socket.io-client-swift#778] opened 2017-08-18 08:25 UTC
This is somewhat related to https://github.com/socketio/socket.io-client-swift/issues/746

If I open then put my app in the background while in my house connected to wifi and then walk out and down the street out of range of the wifi and then open the app I lose connection. **Despite attempting to reconnect repeatedly it won't reconnect**.   Only shutting the app and restarting it will it connect.   However, if I simply turn off wifi with the app in the background it stays connected (switches quickly to cellular I'm assuming).  If I turn on airplane mode and then turn it off again it reconnects.

The same code is called whether it is a connect at startup or a reconnect.  Here is the pertinent code:

`if( socketIOSwift != nil )
    {
        [socketIOSwift disconnect];
   //tried adding this but made no difference -     [socketIOSwift removeAllHandlers];
        socketIOSwift = nil;
    }`
    
`socketIOSwift = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"secure": @YES, @"log": @YES, @"forceWebsockets": @YES, @"cookies": cookies, @"ForceNew": @YES, @"ReconnectAttempts": @50, @"connectParams": properties}];
`
I've been really trying to get to the bottom of this issue, but so far I haven't been able to and today my app didn't pass app review because of it.  Any help is greatly appreciated.

**Comment by nuclearace** [comment] 2017-08-18 15:15
From my experience, automatic reconnect only really functions well when the app is in the foreground. The library has never really been able to handle going from the foreground to the background without adding a bunch of OS dependent code. My solution was to just disconnect the socket when it goes into the background and manually connect when it reenters.

**Comment by bhartsb** [comment] 2017-08-18 18:34
My app has location sharing as a feature and has to send location data when in the background.  Is there anything else you can suggest?

**Comment by nuclearace** [comment] 2017-08-18 20:54
I am not sure I can be of much help in this case. The library itself doesn't handle low level networking, such as determining when a device has switched from wifi to cell (and I don't think it ever should.) So it relies on URLSession when polling and Streams when on WebSockets. If those don't communicate that the connection has broken. Or don't function correctly, there's nothing the library can do.

That being said, can you elaborate on 
>Despite attempting to reconnect repeatedly it won't reconnect.

What do the logs say it is doing?

**Comment by bhartsb** [comment] 2017-08-18 21:06
Can you tell me which logs to look at?  Are you referring to connecting to
xcode and looking at logs from there?

**Comment by bhartsb** [comment] 2017-08-18 21:34
Also, even if the library doesn't handle low-level networking, shouldn't I be able to create a whole new connection without having to close and re-open the app?

**Comment by nuclearace** [comment] 2017-08-18 22:16
>I'm setting the SocketIOClient object to nil so it should be completely released and ready to re-establish a connection, right?
If you're setting the SocketIOClient object to nil you have to create a new one and connect it. At that point it's not "reconnecting" it's a new client. But if you're doing all that, it should connect.

**Comment by bhartsb** [comment] 2017-08-18 23:40
Yes I'm doing it as shown in the code I've posted, and no it is not creating a "new client" nor is it connecting.  Any ideas on what I can do?

**Comment by nuclearace** [comment] 2017-08-19 01:19
I'm not sure what would be the cause then. You'd have to start debugging the client. The logs I'm referring to are the ones when you have the `.log(true)` config set.

**Comment by bhartsb** [comment] 2017-08-19 02:24
Actually I do have it set to true/YES so how do I access this log?  It does
not appear in the list when I connect to the device in
Xcode->window->devices.

**Comment by bhartsb** [comment] 2017-08-19 02:34
I know that I can view the log live in Xcode, but when this issue occurs I'm usually not tethered to my computer.  Is there a way to view the log output (I'm assuming this is console output?) from when the device was not tethered?

**Comment by nuclearace** [comment] 2017-08-19 02:41
That I'm not sure of. You could provide a custom [SocketLogger](https://nuclearace.github.io/Socket.IO-Client-Swift/Protocols/SocketLogger.html) with the [logger](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:FO8SocketIO20SocketIOClientOption6loggerFMS0_FPS_12SocketLogger_S0_) option, but you'd have to define it in Swift.

**Comment by bhartsb** [comment] 2017-08-19 02:57
I found this so I'll try it first:
https://stackoverflow.com/questions/9097424/logging-data-on-device-and-retrieving-the-log

My app is mostly objective c.

BTW, I'd like to propose something. Can you email me directly at bhartsb at
gmail dot com.

**Comment by nuclearace** [comment] 2017-08-19 03:32
@bhartsb Unfortunately, I'm not going to have time to dig deep into this right now. I'll be off-on next week. So you're best bet would be fiddle with it yourself.

**Comment by bhartsb** [comment] 2017-08-19 03:41
Well that is pretty much the direction this has been taking but I would like to propose something longer-term.  As far as this issue I've been "fiddling" with it for months.  I have little idea why it is happening or how to reproduce it reliably, but maybe the logs will give a hint.  I'm going to try again tonight with walking down the street to see if it magically reappears.

**Comment by bhartsb** [comment] 2017-08-19 03:52
I'll just temporarily post my proposition here.  Just FYI this my app: https://drive.google.com/file/d/0B4VrKDriBUuuc1dweWR3enRkcTA/view?usp=sharing

I'm about to release it.  It has been in development a long time.   It depends on numerous open source libraries some more important than others.  I'm wearing too many hats so I'd like to offer stock in exchange for a higher level of support by you for socket.io-client-swift.  Anyway, I thought I'd throw it out there.  

I've often thought that the main committers of open source projects could adopt this model.  Choosing wisely of course which projects they think are likely to go somewhere.

**Comment by nuclearace** [comment] 2017-08-19 04:27
That's an interesting proposition. Not sure I can comment on it much right now though. As for the issue. I can offer some hints.
Since it looks like you're forcing WebSockets, it might actually be an issue with Starscream and how it handles this case. Is it possible to not force websockets?

**Comment by bhartsb** [comment] 2017-08-19 05:14
Yes think over the proposition, and get back to me when and if you want to
negotiate something.  The app has a fair chance at doing well I think.

Per the long polling non-forced web sockets option.  I guess I could, I
tried it and it seems to work.   Long polling as I understand has more
overhead, but can I assume that it will use websockets when possible?  And
I don't know what the issue is with Starscream, but I will take your word
for it.  So I'll try it and see.  Thanks.

**Comment by nuclearace** [comment] 2017-08-19 12:30
The overhead is not that much and yes it will upgrade to WebSockets once it establishes a working polling connection.

**Comment by bhartsb** [comment] 2017-08-22 11:50
@nuclearace So not forcing Websockets doesn't help.   I've gone in and changed my code so that I'm only creating socketIOSwift one time when the app launches, and depending on the reconnects to work.   But the sequence that breaks it most of the time is with cell data off and wifi on open my app.   Put the app in the background and turn on cell data.   Walk out of my house out and walk beyond the range of wifi.  Open the app and note that it won't send data anymore.  The logs don't show anything about disconnecting or reconnecting but the connection goes out to lunch.  

Also per the reconnectWait config is it seconds or milliseconds?

**Comment by bhartsb** [comment] 2017-08-22 12:04
Here's a bit of the log that looks like it is sending something but getting null back:

2017-08-22 03:50:30.616 Pindragon[2688:626246] LOG SocketEngine: Sending ws: 230["getSocketIDsIndicatingUserAliasIsOnline",["jade_socketID","ree_socketID","crystal_socketID","iphone5so4_socketID","iphone6s_socketID","bhartpindragon_socketID","stem_socketID","Handle_socketID","bethany11_socketID","iphone7_socketID","jjhart_socketID","bethany_socketID","iphone6sb_socketID","rio1_socketID","Bethany_socketID","cat_socketID"]] as type: 4
2017-08-22 03:50:30.799 Pindragon[2688:626182] LOG SocketEngine: Got message: 4330[[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]]
2017-08-22 03:50:30.799 Pindragon[2688:626182] LOG SocketIOClient: Should parse message: 330[[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]]
2017-08-22 03:50:30.801 Pindragon[2688:626182] LOG SocketParser: Parsing 330[[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]]
2017-08-22 03:50:30.801 Pindragon[2688:626182] LOG SocketParser: Decoded packet as: SocketPacket {type: 3; data: [<__NSArrayM 0x170c438a0>(
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>,
<null>
)

**Comment by nuclearace** [comment] 2017-08-29 21:22
@bhartsb Sorry the wait, I went on vacation. Yes, `reconnectWait` is currently in seconds.

So it is getting something back? The `330[[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]]` is a bit strange.

**Comment by bhartsb** [comment] 2017-08-29 22:54
@nuclearace Yes, you said you were going to be unavailable so NP. Thanks for clarifying on the reconnectWait.  So I believe the issue turned out to be that  I was reading a pertinent value from the keychain and the keychain sometimes returns nil if it isn't ready.  This was infrequent intermittent behavior which why it took so long to find it.  
I just resubmitted my app to Apple today after fixing a few other issues as well.  My offer is still open if you want to discuss it at some point.  It could be limited to just things related to socket.io-client-swift as they arise or expanded if you were interested to encompass some other backend to client, network and scaling kinds of things as I need help.

**Comment by nuclearace** [comment] 2017-08-29 23:03
@bhartsb so is this issue resolved? If so I'll close the issue.

I appreciate the offer, but I'm pretty busy with work, and with this library and another I have, I don't think I would have enough time to spend to be of any help. I appreciate the offer though.

**Comment by bhartsb** [comment] 2017-08-29 23:23
Okay I understand feel free to reach out if you change your mind as I think the app is likely to do pretty well.  It better because I have years invested into it.

**Closed** 2017-08-30 12:27 UTC
Labels: unconfirmed

**Comment by prgorasiya** [comment] 2018-07-03 08:36
Disconnecting manager first works for me.
My code is as follow
```
socket?.onAny { (data) in
            if data.event == "reconnectAttempt" {
                self.socketManager?.disconnect()
                self.connectSocket()
            }
        }
```
