### ISSUE TITLE
App crashes in v.8.1.2

### ISSUE THREAD

**Issue by jfalexvijay** [socketio/socket.io-client-swift#606] opened 2017-01-12 11:43 UTC
Hi,
    My app is crashing in my customers phone with following error message.
Not sure how to reproduce.. Because it is not at all happening in my available phones.

0	libsystem_kernel.dylib 0x000000018992e314 __semwait_signal + 4
1	libsystem_c.dylib 0x000000018984c15c usleep + 60
2	MyApp 0x000000010026622c function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed, Arg[4] = Owned To Guaranteed> of MyApp.WebSocket.((initStreamsWithData in _F90942689E0E867729C78BA17580A3B5) (data : __ObjC.NSData, Swift.Int) -> ()).(closure #1) (WebSocket.swift:353)
3	MyApp 0x000000010026aed8 partial apply forwarder for MyApp.WebSocket.((initStreamsWithData in _F90942689E0E867729C78BA17580A3B5) (data : __ObjC.NSData, Swift.Int) -> ()).(closure #1) (WebSocket.swift:0)
4	Foundation 0x000000018b422754 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 12
5	Foundation 0x000000018b3672c8 -[NSBlockOperation main] + 92
6	Foundation 0x000000018b3578c4 -[__NSOperationInternal _start:] + 616
7	Foundation 0x000000018b424b00 __NSOQSchedule_f + 224
8	libdispatch.dylib 0x00000001897e91c0 _dispatch_client_callout + 12
9	libdispatch.dylib 0x00000001897f7444 _dispatch_queue_serial_drain + 924
10	libdispatch.dylib 0x00000001897ec9a8 _dispatch_queue_invoke + 648
11	libdispatch.dylib 0x00000001897f938c _dispatch_root_queue_drain + 568
12	libdispatch.dylib 0x00000001897f90ec _dispatch_worker_thread3 + 120
13	libsystem_pthread.dylib 0x00000001899f22b8 _pthread_wqthread + 1284
14	libsystem_pthread.dylib 0x00000001899f1da4 start_wqthread + 0

**Comment by rheza** [comment] 2017-04-14 01:43
Hi, Did you manage to solve this issues ? how ?

I also encounter this when the app is on review by apps team.  Is it because the websockets force on when connection to socket.io server ?, I just resubmitted the app with all optimization set to none flag. hopefully it's run okay now.
----------
Thread 14 name:  Dispatch queue: NSOperationQueue 0x1700381e0 :: NSOperation 0x17024d7a0 (QOS: DEFAULT)
Thread 14:
0   libsystem_kernel.dylib        	0x00000001838ad314 __semwait_signal + 8
1   libsystem_c.dylib             	0x00000001837cc8b0 nanosleep + 212
2   libsystem_c.dylib             	0x00000001837cc7d0 usleep + 64
3   SocketIO                      	0x000000010052f834 specialized WebSocket.(initStreamsWithData(Data, Int) -> ()).(closure #1) (WebSocket.swift:365)
4   SocketIO                      	0x00000001005356c8 partial apply for WebSocket.(initStreamsWithData(Data, Int) -> ()).(closure #1) (WebSocket.swift:0)
5   Foundation                    	0x0000000185381804 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
6   Foundation                    	0x00000001852c6760 -[NSBlockOperation main] + 96
7   Foundation                    	0x00000001852b6b18 -[__NSOperationInternal _start:] + 612
8   Foundation                    	0x0000000185383ba0 __NSOQSchedule_f + 228
9   libdispatch.dylib             	0x000000018376a9a0 _dispatch_client_callout + 16
10  libdispatch.dylib             	0x0000000183778ad4 _dispatch_queue_serial_drain + 928
11  libdispatch.dylib             	0x000000018376e2cc _dispatch_queue_invoke + 884
12  libdispatch.dylib             	0x000000018377aa50 _dispatch_root_queue_drain + 540
13  libdispatch.dylib             	0x000000018377a7d0 _dispatch_worker_thread3 + 124
14  libsystem_pthread.dylib       	0x00000001839731d0 _pthread_wqthread + 1096
15  libsystem_pthread.dylib       	0x0000000183972d7c start_wqthread + 4
------------------
Thanks

**Comment by nuclearace** [comment] 2017-04-14 11:44
I see this particular crash being reported but I have no idea how to reproduce myself.

**Comment by nuclearace** [comment] 2017-07-04 14:17
Probably fixed in the DispatchQueue refactors.

**Closed by nuclearace** 2017-07-04 14:17 UTC
