### ISSUE TITLE
Error:Session ID unknown???

### ISSUE THREAD

**Issue by ysfox** [socketio/socket.io-client-swift#374] opened 2016-05-26 03:02 UTC
I get the error 'Session ID unknown' after I disconnect with our socketIO server(with the JS version),our client is iOS,in first connected,I can access our socketIO server and an AM with our server,but I disconnect and then connected again,I will get the error  'Session ID unknown'???
I print the log,the log show oder is：
（1）fist show ‘Disconnect’,then auto get a error 'Session ID unknown',after it i connect our server,the server get my request，but,I con't AM with my server?
How to get the problem? HELP? TKS

**Comment by nuclearace** [comment] 2016-05-26 15:45
What version are you on?

**Comment by JunfeiW** [comment] 2016-06-06 13:31
I came across the same problem with the latest version of socket.io node (1.4.2), and socket.io-swift(6.1.2)

**Comment by nuclearace** [comment] 2016-06-06 14:01
I noticed it too, it's because after calling disconnect it does another long poll, which it shouldn't.

**Comment by orozkoinsider** [comment] 2016-06-06 16:33
Same here, when writing some data in the socket I get the same error. 
My log:
LOG SocketEngine: Got message: 3
LOG SocketEnginePolling: Got polling response
LOG SocketEnginePolling: Doing polling request
LOG SocketEngine: Writing poll:  has data: 0
LOG SocketEnginePolling: Sending poll:  as type: 2
LOG SocketEnginePolling: Created POST string: 1:2
LOG SocketEnginePolling: POSTing
LOG SocketEnginePolling: Doing polling request
LOG SocketEnginePolling: Got polling response
LOG SocketEnginePolling: Doing polling request
LOG SocketEngine: Got message: {"code":1,"message":"Session ID unknown"}
ERROR SocketEngine: Session ID unknown
ERROR SocketIOClient: Session ID unknown
LOG SocketIOClient: Handling event: error with data: (
    "Session ID unknown"
)
I also noticed that if I force the websockets the connection can´t even be stablished.

My log when I force the websockets:
LOG SocketIOClient: Adding handler for event: loginResponse
LOG SocketIOClient: Starting reconnect
LOG SocketIOClient: Handling event: reconnect with data: (
    "Socket Disconnected"
)
LOG SocketIOClient: Trying to reconnect
LOG SocketIOClient: Handling event: reconnectAttempt with data: (
    "-1"
)

**Comment by nuclearace** [comment] 2016-06-06 18:40
@orozkoinsider is your server node.js based or something else. Because I've had people say that non-node.js servers don't allow WebSocket first.

**Comment by orozkoinsider** [comment] 2016-06-07 09:44
@nuclearace does the library store the cookies when pulling to maintain the connection? maybe in android and web library this cookie is stored somewhere

**Comment by nuclearace** [comment] 2016-06-07 14:04
Socket.io doesn't use cookies by default

**Comment by nuclearace** [comment] 2016-06-07 14:05
Your error looks different than the one that happens when you disconnect. I've been able to reproduce the disconnect error, it's a logic error where the client is doing a poll after it sends a disconnect. It's not really a big problem, just a slight annoyance.

**Comment by nuclearace** [comment] 2016-06-07 17:13
@ysfox @JunfeiW you can see if the latest development fixes the problem

**Comment by JunfeiW** [comment] 2016-06-17 05:56
@nuclearace, I have tried the latest development version. I can't reproduced the error anymore.
So I think it should be fixed.

**Comment by JunfeiW** [comment] 2016-06-17 05:57
I will try to check it in the future usage, if any problem, I will notify it here.

**Closed** 2016-06-17 14:07 UTC
Labels: bug
