### ISSUE TITLE
 Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by chirag225** [socketio/socket.io-client-swift#786] opened 2017-08-23 10:47 UTC
pod 'Socket.IO-Client-Swift', '~> 11.1.0'     Xcode 8.3.3

1 ) Could not build module 'SocketIO'
2 ) Property with 'retain (or strong)' attribute must be of object type for @property (nonatomic, strong) dispatch_queue_t _Nonnull handleQueue;

**Comment by nuclearace** [comment] 2017-08-29 12:58
Duplicate of #715

**Closed by nuclearace** 2017-08-29 12:58 UTC
Labels: duplicate
