### ISSUE TITLE
v11 not working anymore with Carthage

### ISSUE THREAD

**Issue by tbaranes** [socketio/socket.io-client-swift#787] opened 2017-08-28 15:44 UTC
```
dyld: Library not loaded: @rpath/StarscreamSocketIO.framework/StarscreamSocketIO
  Referenced from: /private/var/containers/Bundle/Application/4B73A5DE-1291-4094-BC0D-9C429EAD039E/KaraFun.app/Frameworks/SocketIO.framework/SocketIO
  Reason: image not found
```

It was working as expected in the 10.x, is it due to the starscream migration?

**Comment by nuclearace** [comment] 2017-08-28 16:16
This is probably related to #754. For which there is only a [workaround](https://github.com/socketio/socket.io-client-swift/issues/754#issuecomment-324758739). I haven't thought of a good solution to this issue.

**Comment by AOrumbaev** [comment] 2017-08-28 19:48
Does not work on Xcode beta 6 & iOS 11 beta 8.
Though worked fine after cleaning & removing derived data and running on Xcode 8.3.3 & iOS 10.3.3

**Comment by nuclearace** [comment] 2017-08-28 21:19
@AOrumbaev correct. Beta version are not supported in any official capacity. There is a swift4 branch but there is no guarantee that it works or even builds.

**Comment by nuclearace** [comment] 2017-08-29 12:08
Closing as a duplicate of #772.

**Closed by nuclearace** 2017-08-29 12:08 UTC
