### ISSUE TITLE
Need way to set internal timeout

### ISSUE THREAD

**Issue by thully** [socketio/socket.io-client-swift#883] opened 2017-11-27 20:34 UTC
When using the library, it will try to connect for a period of time before emitting an error/status change event and re-attempting the connection. This is distinct from the timeout option, which is optional and specifies a time period to attempt connection before giving up. 

If the timeout is set to be longer than the built-in timeout (60s), it will never be called. As such, what we need is a way to set the internal timeout in the options. That would allow longer or shorter timeouts.

**Comment by nuclearace** [comment] 2017-11-27 21:05
Duplicate of https://github.com/socketio/socket.io-client-swift/issues/587

**Closed by nuclearace** 2017-11-27 21:05 UTC
