### ISSUE TITLE
disconnect event fired before server recognizes disconnect

### ISSUE THREAD

**Issue by 2fours** [socketio/socket.io-client-swift#215] opened 2015-10-18 21:28 UTC
Sometimes when I call disconnect on the client the socket is immediately disconnected on the server. Other times it seems to take ~30 seconds. Is there anyway to make this consistent?

**Comment by nuclearace** [comment] 2015-10-18 21:33
How are you calling disconnect? From the main thread?

**Comment by 2fours** [comment] 2015-10-18 21:37
I call it from this event: [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(pause:) name:UIApplicationDidEnterBackgroundNotification object:nil];

**Comment by nuclearace** [comment] 2015-10-18 21:42
That's going to run into the problem where the app is going to get suspended before it can disconnect. I've never really thought a good platform neutral solution to it.

**Comment by 2fours** [comment] 2015-10-18 21:44
Assuming we're on iOS is there a way to do it consistently?

**Comment by nuclearace** [comment] 2015-10-18 21:47
I really wouldn't know, I'm not an iOS dev. But perhaps some sort of background task

**Comment by meismyles** [comment] 2015-10-18 21:58
You just trying to close the socket when the app enters the background?

**Comment by meismyles** [comment] 2015-10-18 22:05
Well if you are, you may want to close it in the methods in `AppDelegate` rather than relying on notifications.

For example, either of these depending on your application type:

    func applicationDidEnterBackground(application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    ...

    func applicationWillTerminate(application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        UIApplication.sharedApplication().endReceivingRemoteControlEvents()
    }

**Comment by 2fours** [comment] 2015-10-18 22:06
Correct.

**Comment by meismyles** [comment] 2015-10-18 22:09
See my last message. Also, those methods are app wide so you don't need to worry about closing the socket in every view like you would with your method.

**Comment by 2fours** [comment] 2015-10-19 00:30
@meismyles thanks I tried closing it from appdelegate, and also tried using [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:  neither seemed to make any difference.

**Comment by meismyles** [comment] 2015-10-19 16:28
Weird. The second I close the socket or kill my app it closes immediately.

**Comment by 2fours** [comment] 2015-10-19 16:46
Weird I'll see if I can reproduce the issue in a test project.

**Comment by nuclearace** [comment] 2015-10-19 16:49
I don't doubt that you're running into this issue. I would chalk it up to iOS's limitations

**Comment by 2fours** [comment] 2015-10-19 16:58
If I can make a simple project to reproduce the issue does that help? I didn't have this problem with 0.9.x.

**Comment by 2fours** [comment] 2015-10-19 19:14
If I use the simulator with iphone 6s and ios 9 it seems to work fine. I'm seeing the issues on an iphone 4 with 7.1.

**Comment by 2fours** [comment] 2015-10-19 20:20
Think I got this working. On 7.1.2 it seems the socket connection is put into a state where it can't send or receive from the server a lot more aggressively than on 8+ when home is pressed. If I configure things to use the voip background mode then the socket seems to disconnect every time. Not sure if this is the best solution but beginBackgroundTaskWithExpirationHandler: didn't seem to work.

**Comment by meismyles** [comment] 2015-10-19 20:22
Just a warning, if you set that background mode and the application doesn't actually do it, it will be rejected from the app store.

**Comment by 2fours** [comment] 2015-10-19 20:25
Doesn't actually do voip stuff? How else could we get around it then. I can see when the app resumes that the disconnect completes, so 7.1.2 is definitely "pausing" the socket when home is pressed.

**Comment by nuclearace** [comment] 2015-10-19 20:27
That's expected behavior. When apps go into the background they get suspended. One solution is to change the server's timeout. Or just have it so you're not relying on when a socket disconnects

**Comment by meismyles** [comment] 2015-10-19 20:28
Yeah, if it doesn't actually perform the background operation type you specify then it will be rejected. How are you determining the socket hasn't disconnected, from the server or the app?

**Comment by 2fours** [comment] 2015-10-19 20:29
From the server.

**Comment by nuclearace** [comment] 2015-10-19 20:33
There's one change I could make, but I'm not sure it would really do anything.

**Comment by meismyles** [comment] 2015-10-19 20:35
Well I honestly can't think of a reason why it doesn't close. I assume you are calling the `close()` method on the socket instance and not just waiting for the app to kill it when its removed from memory?

I've just tested by adding the close call in my AppDelegate:

    func applicationDidEnterBackground(application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
        SocketHandler.sharedInstance.socket.close()
    }

Tested it about 30 times and it closed immediately every time.

**Comment by 2fours** [comment] 2015-10-19 20:35
On 7.1.2?

**Comment by meismyles** [comment] 2015-10-19 20:37
Ah woopsie. Read your earlier comment the wrong way round, as in working on v7 and **not** working on v9.

I'll see if I can test it on v7 now.

**Comment by nuclearace** [comment] 2015-10-19 20:41
https://github.com/socketio/socket.io-client-swift/commit/02971e14c2d59ef3ade6e6e6c1ef876a4485b964 is about the only thing I can think to do

**Comment by meismyles** [comment] 2015-10-19 20:43
Can't install iOS 7 simulators in El Cap so guess thats me out sorry.

**Comment by nuclearace** [comment] 2015-10-19 20:45
Yeah, at this point it's better not trying to support iOS 7 anymore.

**Comment by 2fours** [comment] 2015-10-19 20:45
Thanks I will try this and see if it helps.

**Comment by 2fours** [comment] 2015-10-19 21:05
02971e1 doesn't seem to make any difference. Thanks everyone for your help.

**Comment by meismyles** [comment] 2015-10-19 21:07
Odd. Does it matter that the connection hangs on? If its really necessary to close it, a bit of a dirty hack but what about sending a message from the device to the server so that the server can close the connection?

**Comment by 2fours** [comment] 2015-10-19 21:09
The websocket close is implemented by sending a message from the device to the server. I'm using it to determine if the client is connected for the purpose of incrementing the badgenum new message count so the more timely it disconnects the better.

**Comment by nuclearace** [comment] 2015-10-19 21:14
The problem is the server doesn't know the connection is closed until the ping timeout.

**Comment by meismyles** [comment] 2015-10-19 21:25
So does the app not send the disconnect message, or the server not receive it? Or the server receives it but doesn't disconnect the socket?

**Comment by nuclearace** [comment] 2015-10-19 21:26
His app is getting suspended before it send the message

**Comment by meismyles** [comment] 2015-10-19 21:39
Well I'd definitely be disconnecting it in AppDelegate rather than using notifications. Notifications may not be received immediately and so the app could already be in the background.

But if you're disconnecting it in AppDelegate I don't see why it wouldn't do it. I've never seen any reports of things not working in the methods in AppDelegate unless the application is set up incorrectly regarding background modes. It should finish executing whatever is in there before it finally is suspended (unless it takes a very long period of time, e.g. > 3 mins in which case the OS may forcefully kill it). But this is an incredibly quick task. Are the methods in AppDelegate definitely being called? If you put a print statement before and after the close call are they both executed?

**Comment by 2fours** [comment] 2015-10-19 22:16
Think I found something. 

I put back the beginBackgroundTaskWithExpirationHandler: code with one change, I was calling endBackgroundTask when the socket disconnect event was received. If I comment this out it seems to disconnect every time.

 [self.socket on:@"disconnect" callback:^(NSArray * data, SocketAckEmitter * ack) {
        DDLogInfo(@"socket disconnect");
     //   [[UIApplication sharedApplication] endBackgroundTask:_bgTaskId];
    }];

This seems to indicate there is some sort of timing issue between the socket actually being disconnected and the socket disconnect event being fired.

**Comment by meismyles** [comment] 2015-10-19 22:56
Personally I wouldn't use `beginBackgroundTaskWithExpirationHandler` for this. I don't really see closing the socket as a background task that still needs to be executed? If you see the top answer of this there are some potential downsides to using this: http://stackoverflow.com/questions/12071726/how-to-use-beginbackgroundtaskwithexpirationhandler-for-already-running-task-in

Can't you just call socket.close() in `applicationWillTerminate: `? And make sure you have `Application does not run in background` set to `YES` in your `info.plist`.
Do you need to listen for the disconnect event on the device? Can't you just assume that if the application is closed then the socket is closed?

**Comment by 2fours** [comment] 2015-10-19 23:08
The documentation for applicationDidEnterBackground states that you only get 5 seconds: 

`
Your implementation of this method has approximately five seconds to perform any tasks and return. If you need additional time to perform any final tasks, you can request additional execution time from the system by calling beginBackgroundTaskWithExpirationHandler:. In practice, you should return from applicationDidEnterBackground: as quickly as possible. If the method does not return before time runs out your app is terminated and purged from memory.
`

I'd rather use beginBackgroundTaskWithExpirationHandler and have more control over that time. I'm already using it elsewhere and it works well. I agree that closing the socket shouldn't need to be a background task - apparently on iOS > 7.1.2 this is the case. I don't need to listen for the disconnect on the device and now that I've uncovered the behavior I won't, but I still think the behavior is strange and should be looked at by the developer of the library. Thanks.

**Comment by 2fours** [comment] 2015-10-19 23:39
Not sure if this helps but I put some logging in the doDisconnect function of WebSocket.swift and it looks like doDisconnect gets called twice:
```
2015-10-19 17:29:32.261 surespot[1694:8617] Log WebSocket: doDisconnect, 0, error: Optional(Error Domain=Websocket Code=1000 "connection closed by server" UserInfo=0x17d22360 {NSLocalizedDescription=connection closed by server})
2015-10-19 17:29:32.272 surespot[1694:8617] Log WebSocket: doDisconnect, 0, error: nil
```

So perhaps the first doDisconnect is getting called prematurely?

**Comment by nuclearace** [comment] 2015-12-03 17:04
Is this still a problem?

**Comment by Glagnar** [comment] 2015-12-11 13:29
I have the issue where eventough the client closes the connection, the server only gets the disconnect event after about 30 seconds.
```swift
private var socket: SocketIOClient?
public func stopConnection() {
   debugPrint("Remote Connection Closing")
   socket?.close()
   socket = nil
}
```
In my case, the client disconnects and does some cleanup in the 
```
socket?.on("disconnect")
```
but the server waits for 30 seconds before firing the disconnect.
Running iOS 7.2 btw.

**Comment by Farbod909** [comment] 2015-12-30 20:24
Hi,

I'm not sure if this applies to you guys, but I found that the best way that socket io has been working for me is with the use of a singleton.

I created the following singleton class:

```Swift
class SocketIOManager {
    
    static let sharedInstance = SocketIOManager()
    
    var socket: SocketIOClient
    
    init() {
        
       self.socket = SocketIOClient(
                socketURL: "someUrl.com",
                options: [.ForcePolling(true)]
       )

    }
    
    func connectSocket() {
        self.socket.connect()
    }
    func disconnectSocket() {
        self.socket.disconnect()
    }
    func socketStatus() -> SocketIOClientStatus {
        return socket.status
    }
    
}
```
and then I created a shared instance above the AppDelegate class
```
let socketIOManager = SocketIOManager()
```

After doing all that, I can easily call ```socketIOManager.connectSocket()``` and ```socketIOManager.disconnectSocket()``` anywhere and it connects and disconnects from the server immediately.

I'm sorry if this is not what you are looking for, but I also had a problem where the server was not receiving my disconnect event, so I figured I'd post my solution here. In my case, I'm assuming the problem was because multiple instances of the ```socket``` variable were being created and calling socket.disconnect() may not have been disconnecting the correct instance. Creating a singleton makes sure there is only one instance.

**Comment by 2fours** [comment] 2016-03-30 01:06
Not seeing this anymore with https://github.com/socketio/socket.io-client-swift/commit/6c779e84d2d3ae079db9fba536c6c1755409a875 and 1.4.5 on the server.

**Closed** 2016-04-16 14:25 UTC
