### ISSUE TITLE
Redefinition of module 'SSCZLib' e 'SSCommonCrypto'

### ISSUE THREAD

**Issue by freedoom1984** [socketio/socket.io-client-swift#791] opened 2017-08-31 12:56 UTC
I add the socket.io with cartfile:

github "nuclearace/Starscream" ~> 8.0.4
github "socketio/socket.io-client-swift" ~> 11.1.1

When I add the static library and try the import I look this build error:
Redefinition of module 'SSCZLib'
Redefinition of module 'SSCommonCrypto'

Thanks

**Comment by nuclearace** [comment] 2017-08-31 13:27
Duplicate of #754. If you add `github "socketio/socket.io-client-swift" "development"` Does it fix it? If yes I'll make a new release today.

**Closed by nuclearace** 2017-08-31 13:27 UTC
