### ISSUE TITLE
Build error: module redefinitions

### ISSUE THREAD

**Issue by Patrick-Remy** [socketio/socket.io-client-swift#782] opened 2017-08-22 14:21 UTC
I tried to use it with carthage in my project, but I get following errors:

```
.../Carthage/Checkouts/Starscream/zlib/module.modulemap:1:8: error: redefinition of module 'SSCZLib'
module SSCZLib [system] {
       ^
.../Carthage/Checkouts/socket.io-client-swift/Source/Starscream/zlib/module.modulemap:1:8: note: previously defined here
module SSCZLib [system] {
       ^
.../Carthage/Checkouts/Starscream/zlib/module.modulemap:6:8: error: redefinition of module 'SSCommonCrypto'
module SSCommonCrypto [system] {
       ^
.../Carthage/Checkouts/socket.io-client-swift/Source/Starscream/zlib/module.modulemap:6:8: note: previously defined here
module SSCommonCrypto [system] {
       ^
<unknown>:0: error: merge-module command failed with exit code 1 (use -v to see invocation)
```

Cartfile:
```
github "nuclearace/Starscream" ~> 8.0.3
github "socketio/socket.io-client-swift" "master"
```

When I remove Starscream and only build with socket.io, I get the runtime error: `dyld: Library not loaded: @rpath/StarscreamSocketIO.framework/StarscreamSocketIO`
When building with the master branch from Starscream, no StarscreamSocketIO.framework is built.

I am using the latest Xcode 9 beta 6.

**Comment by nuclearace** [comment] 2017-08-22 14:34
Duplicate of #772. I think it's related to the sub module this library has for testing. Is there a way to tell Carthage not to init submodules on the client side? I think the long term solution is to add a Cartfile to this project. But I won't be able to do that today I don't think

**Closed by nuclearace** 2017-08-22 14:34 UTC

**Comment by Patrick-Remy** [comment] 2017-08-22 14:39
Unfortunately not, also I am using a library that needs submodules in the same Cartfile..
