### ISSUE TITLE
xcode 10.2 compiling Errors On Simulator

### ISSUE THREAD

**Issue by darkerk** [socketio/socket.io-client-swift#1175] opened 2019-03-26 08:18 UTC
There was an error compiling on the Simulator, but it was good to work on my iPhone.
<img width="1858" alt="2019-03-26_4 11 38" src="https://user-images.githubusercontent.com/1670251/54981134-89866400-4fe2-11e9-919f-110cd18a5afd.png">

**Comment by cbiggin** [comment] 2019-03-26 15:14
I'm having pretty much the exact same issue. Compiling fine for device but not in the simulator. Also, I am building my SocketIO framework for device & simulator and then lipo'ing the binaries.

I was able to over-come it by dragging the SocketIO project directly into my own. BTW, everything was working fine in Xcode 10.1 so this is new for 10.2.

**Comment by cbiggin** [comment] 2019-03-26 16:09
I've attached a small test project which demonstrates the problem.

[SocketIOTest.zip](https://github.com/socketio/socket.io-client-swift/files/3009049/SocketIOTest.zip)

**Comment by nuclearace** [comment] 2019-03-26 16:23
@cbiggin Thanks, that's very helpful, I'll take a look at that when I get a chance.

**Comment by nuclearace** [comment] 2019-03-26 16:24
I wonder if this is a Swift bug? I don't recall seeing anything in Swift evolution that would affect this.

**Comment by nuclearace** [comment] 2019-03-26 16:32
@cbiggin It looks like if you forward declare that class, it can build. And it also looks like you need a copy files phase to add copy the frameworks in.

**Comment by nuclearace** [comment] 2019-03-26 16:32
```objective-c
@class SocketManager;

@import SocketIO;

@interface ViewController ()
@property (strong, nonatomic) SocketManager *manager;
@end

@implementation ViewController

- (void)viewDidLoad {
	[super viewDidLoad];
	// Do any additional setup after loading the view.
}


@end
```

**Comment by nuclearace** [comment] 2019-03-26 17:24
Hm... I'm not quite sure in that case. Let me play around a bit more

**Comment by nuclearace** [comment] 2019-03-26 17:26
I was able to get it to work with CocoaPods and the 15 beta.

**Comment by paulosaure** [comment] 2019-03-26 17:27
Strange. Here is the updated project (Using carthage)

[SocketIOTest.zip](https://github.com/socketio/socket.io-client-swift/files/3009436/SocketIOTest.zip)

**Comment by nuclearace** [comment] 2019-03-26 17:33
@paulosaure Is that using the beta version?

**Comment by paulosaure** [comment] 2019-03-26 17:34
Yes

**Comment by nuclearace** [comment] 2019-03-26 17:37
Yeah I see. It's also odd because I also see the definition for `SocketManager` in the exported interface.

**Comment by paulosaure** [comment] 2019-03-26 17:39
And my carthage version is up to date (0.32)

**Comment by cbiggin** [comment] 2019-03-26 17:46
@nuclearace Yeah, I just wanted to quickly demonstrate in as simple a project as possible (ie, File -> New -> Project; add the Frameworks & declaration) what the problem is. And yes, does require a `copy frameworks`.

I thought at first that it was module naming, but no, checked that. Checked the valid architectures and they seem ok. Checked my lipo'd frameworks, also ok. My next thought is possibly Objective-C issue? Has any body done a Swift only project?

**Comment by nuclearace** [comment] 2019-03-26 17:48
I've only tested with CocoaPods so far. I haven't setup a carthage project in a while.

**Comment by paulosaure** [comment] 2019-03-26 17:49
> @nuclearace Yeah, I just wanted to quickly demonstrate in as simple a project as possible (ie, File -> New -> Project; add the Frameworks & declaration) what the problem is. And yes, does require a `copy frameworks`.
> 
> I thought at first that it was module naming, but no, checked that. Checked the valid architectures and they seem ok. Checked my lipo'd frameworks, also ok. My next thought is possibly Objective-C issue? Has any body done a Swift only project?

My updated version is with `copy frameworks`

**Comment by nuclearace** [comment] 2019-03-26 17:53
I'm wondering if this is some Carthage thing, because CocoaPods doesn't seem to have any issue with symbol discovery, even when it's in Objective-C.

**Comment by paulosaure** [comment] 2019-03-26 17:55
Seems weird since it worked with Xcode 10.1 + Carthage 0.32

**Comment by paulosaure** [comment] 2019-03-26 17:58
Ok, seems related to carthage
==> https://github.com/Carthage/Carthage/issues/2745

**Comment by nuclearace** [comment] 2019-03-26 18:08
Having just went through the steps of trying to add this via a Carthage project and running into the same issue, I'm inclined to say it is a bug with Carthage.

**Comment by cbiggin** [comment] 2019-03-26 18:08
@paulosaure I'm not using Carthage. I'm manually creating my frameworks using `lipo`.

**Comment by cbiggin** [comment] 2019-03-26 18:08
BTW, quickly created a Swift project and same thing.

**Comment by nuclearace** [comment] 2019-03-26 18:09
Well... In that case, maybe it's a bug in the Swift Objective-C exporter...

**Comment by nuclearace** [comment] 2019-03-26 18:15
>BTW, quickly created a Swift project and same thing.

How are you importing the framework?

**Comment by nicolasgoutaland** [comment] 2019-03-26 20:46
May be related to this https://github.com/Carthage/Carthage/pull/2723

**Comment by darkerk** [comment] 2019-03-27 03:16
@nicolasgoutaland Yeah, I've tested the latest source code  and it to work fine, So Waiting for Carthage release version.

**Comment by nuclearace** [comment] 2019-03-28 11:19
Given how this appears to be an issue with dependency managers and not the actual library, I'm going to close this out.

**Closed by nuclearace** 2019-03-28 11:19 UTC
