### ISSUE TITLE
Attempted to create a task in a session that has been invalidated

### ISSUE THREAD

**Issue by MishraVikas1** [socketio/socket.io-client-swift#364] opened 2016-05-05 10:06 UTC
Its crashing at "session?.dataTaskWithRequest(req, completionHandler: callback).resume()" this line which is in SocketEnginePollable.swift
Since, I have added through cocoapods, I can't make changes in frameworks until we unlock which we should not prefer.

**Comment by nuclearace** [comment] 2016-05-05 12:53
duplicate of #356

**Closed by nuclearace** 2016-05-05 12:53 UTC
