### ISSUE TITLE
Problem with emitWithAck being called consecutively

### ISSUE THREAD

**Issue by CallumOz** [socketio/socket.io-client-swift#43] opened 2015-04-02 16:21 UTC
Hi,

I have a node-js server running, everything is fine, except for one little problem.
When emitWithAck is called twice, one after the other, the second emit fails one out of every ten times.
Each event emitted is different, and the server doesn't seem to receive the second event at all when it fails.
If I swap the 2 emitWithAck's around, then it's the new second one that fails.

My code looks like this:
```
self.socket.emitWithAck("event1", ...)
self.socket.emitWithAck("event2", ...)
```

I hope that's enough information, even though I doubt it, it's a start at least ;)

Callum

**Comment by nuclearace** [comment] 2015-04-02 16:44
Are you on the latest version? I'm having trouble reproducing.

**Comment by nuclearace** [comment] 2015-04-02 16:47
If so can you provide a minimal server example that reproduces it.

**Comment by nuclearace** [comment] 2015-04-02 16:50
Because it sounds similar to https://github.com/nuclearace/Socket.IO-Client-Swift/issues/27

**Comment by CallumOz** [comment] 2015-04-02 19:24
I am working on an application that communicates with [Let's Chat](https://github.com/sdelements/lets-chat)
The events that I have the problems with are "account:whoami" and "rooms:list".
I am using the latest Cocoapod version 1.4.4

**Comment by nuclearace** [comment] 2015-04-03 12:42
Hm, are you sending these emitWithAcks as soon as you connect? I'm noticing a case if you're using polling/websockets the server sometimes doesn't respond to them.

**Comment by nuclearace** [comment] 2015-04-03 12:52
Found a race condition

**Comment by CallumOz** [comment] 2015-04-03 12:55
Yes these emitWithAcks are sent in the callback:
```
self.socket.on("connect") { [weak self] data, ack in
        ...
}

```

**Comment by nuclearace** [comment] 2015-04-03 13:19
Actually finding a few bugs

**Comment by nuclearace** [comment] 2015-04-03 13:37
In the meantime, you can try setting a timeout on the ack, and then if you get `"No ACK"` in the ack reply you can resend it. Or you can try forcing WebSockets or polling. Should have a fix by later today

**Comment by nuclearace** [comment] 2015-04-03 20:24
Should be fixed from https://github.com/socketio/socket.io-client-swift/pull/44

**Closed by nuclearace** 2015-04-03 20:24 UTC
Labels: bug, in progress
