### ISSUE TITLE
Crash in SocketEngineSpec and SocketEngine

### ISSUE THREAD

**Issue by yxztj** [socketio/socket.io-client-swift#463] opened 2016-08-22 07:50 UTC
We've been using socket io client library(latest is 6.0) in production for several months, and we received some issues from Fabric. Unfortunately all of them are hard to repro(<1%), so we'are not able to provide detailed steps to repro. 

Anyway it might be useful to send the information to you :)

<img width="973" alt="screen shot 2016-08-22 at 3 37 52 pm" src="https://cloud.githubusercontent.com/assets/3334458/17847259/affaa378-687f-11e6-95f8-79a13133f759.png">
<img width="948" alt="screen shot 2016-08-22 at 3 47 29 pm" src="https://cloud.githubusercontent.com/assets/3334458/17847313/e49a342c-687f-11e6-89e8-e75cd4914c75.png">
<img width="765" alt="screen shot 2016-08-22 at 3 48 52 pm" src="https://cloud.githubusercontent.com/assets/3334458/17847323/f5da7152-687f-11e6-8025-8c1d28a6a563.png">

Please let us know if you need any additional information

**Comment by nuclearace** [comment] 2016-08-22 15:17
Yeah I'm not sure this is enough information. I would need a way to reproduce reliably.

**Comment by yxztj** [comment] 2016-08-23 02:12
@nuclearace Yes we know it's important to reproduce the issues. But due to low repro rate and uncertain scenario with end users, it's really hard for us to narrow down that way.

Also we don't want to leave the crashes there. Are there any possible code paths that might lead to crashes with the stack traces above?

**Comment by nuclearace** [comment] 2016-08-26 14:52
I have no idea, it could be because of the engine being released before it's connected. But this is all hard to debug.

**Comment by hifall** [comment] 2016-08-28 02:16
I just saw this crash on my iPhone.

**Comment by yxztj** [comment] 2016-09-21 07:22
@nuclearace In our code sometimes we create a new SocketIOClient instance to replace the old one, regardless which state the old client is in. Is it safer that we hold the reference to the old one and check the state before releasing it?

**Comment by yxztj** [comment] 2016-10-19 08:24
@nuclearace I think I might have found something. There are 2 threads calling createWebsocketAndConnect at the same time, leading to **race condition**.

In engineHandleQueue thread, SocketEngine would recreate the websocket on SocketEngine.websocketDidDisconnect.
<img width="1024" alt="screen shot 2016-10-19 at 4 19 19 pm" src="https://cloud.githubusercontent.com/assets/3334458/19510996/0562ba7e-9618-11e6-87cb-ddaab87562f8.png">

Meanwhile, on main thread SocketIOClient is also creating websocket in _tryReconnect:
<img width="1282" alt="screen shot 2016-10-19 at 4 19 26 pm" src="https://cloud.githubusercontent.com/assets/3334458/19511089/57e6ee82-9618-11e6-8a0c-e784037aee43.png">

Since both threads are calling the same function, there should be some unexpected behaviors.
Could there be any fix based on the investigation above?

**Comment by nuclearace** [comment] 2017-07-04 14:00
Most likely fixed with the DispatchQueue refactoring.

**Closed by nuclearace** 2017-07-04 14:00 UTC
